# Generated by Django 2.0.2 on 2019-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_complaint_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('resolved', 'resolved'), ('spam', 'spam'), ('reassign', 'reassign')], default='unresolved', max_length=15),
        ),
    ]
