# Generated by Django 2.2.3 on 2019-07-04 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_auto_20190703_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
