# Generated by Django 2.2.3 on 2019-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0014_complaint_resolved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(),
        ),
    ]
