# Generated by Django 2.2.3 on 2019-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0015_auto_20190704_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
