# Generated by Django 2.2.3 on 2019-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0016_auto_20190704_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
