# Generated by Django 2.2.3 on 2019-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0017_auto_20190704_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
